### PR TITLE
Update to mtl-2.2.2

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by int-index** [comment]
```
src/Ether/Reader.hs:142:39: error:
    • Expecting one more argument to ‘m’
      Expected a type, but ‘m’ has kind ‘k2 -> *’
    • In the type ‘m’
      In the first argument of ‘coerce’, namely ‘(T.runReaderT @r @m @a)’
      In the expression: coerce (T.runReaderT @r @m @a)
    • Relevant bindings include
        runReaderT :: ReaderT tag r m2 a -> r -> m2 a
          (bound at src/Ether/Reader.hs:142:1)
    |
142 | runReaderT = coerce (T.runReaderT @r @m @a)
    |                                       ^
src/Ether/Reader.hs:206:40: error:
    • Expecting one more argument to ‘m’
      Expected a type, but ‘m’ has kind ‘k2 -> *’
    • In the type ‘m’
      In the first argument of ‘coerce’, namely ‘(T.runReaderT @p @m @a)’
      In the expression: coerce (T.runReaderT @p @m @a)
    • Relevant bindings include
        runReadersT :: ReadersT p m2 a -> p -> m2 a
          (bound at src/Ether/Reader.hs:206:1)
    |
206 | runReadersT = coerce (T.runReaderT @p @m @a)
    |                                        ^
```

**Comment by ghost** [comment]
Builds fine with 8.6.4 and 8.6.5... Maybe there was a regression in 8.2-8.4?
